<?php

/**
 * @file
 * Install, update, and uninstall functions for the File Tree module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_install().
 */
function filetree_install($is_syncing): void {
  if (!$is_syncing) {
    \Drupal::messenger()->addWarning(t('File Tree has been installed. Before this does anything, File Tree needs to be added to one or more text formats. Visit the <a href=":formats">text format administration</a> to set up this filter.', [
      ':formats' => Url::fromRoute('entity.filter_format.collection')->toString(),
    ]));
  }
}
